spring:
  application:
    name: task-tracker

  datasource:
    url: jdbc:h2:file:./data/mephi12;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    username: mephi12
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api
  port: 8083
