spring:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access.lifetime: ${ACCESS_TOKEN_LIFETIME}

  application:
    name: task-tracker

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api
  port: 8083
